<?php
$message = "This is a sample PHP file that is generated by AI.";
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=7">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="theme-color" content="#4CAF50">
        <link rel="apple-touch-icon" sizes="57x57" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="https://saiaaaaaaa.github.io/my-website/resources/icon/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="https://saiaaaaaaa.github.io/my-website/resources/icon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="https://saiaaaaaaa.github.io/my-website/resources/icon/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="https://saiaaaaaaa.github.io/my-website/resources/icon/favicon-16x16.png">
        <link rel="manifest" href="https://saiaaaaaaa.github.io/my-website/resources/icon/manifest.json">
        <meta name="msapplication-TileColor" content="#4CAF50">
        <meta name="msapplication-TileImage" content="https://saiaaaaaaa.github.io/my-website/resources/icon/ms-icon-144x144.png">
        <title>Sample Portfolio Page</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
                background-color: #f9f9f9;
                color: #333;
            }

            header {
                background-color: #4CAF50;
                padding: 20px;
                color: white;
                text-align: center;
            }

            nav {
                background-color: #333;
                overflow: hidden;
            }

            nav a {
                float: left;
                display: block;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

            nav a:hover {
                background-color: #ddd;
                color: black;
            }

            section {
                padding: 20px;
            }

            .project {
                border: 1px solid #ccc;
                margin-bottom: 20px;
                padding: 15px;
                border-radius: 5px;
                background-color: white;
            }

            footer {
                background-color: #4CAF50;
                color: white;
                text-align: center;
                padding: 10px;
            }

            /* This HTML file was generated by ChatGPT, not written by a human. */
        </style>
    </head>
    <body>
        <header>
            <h1>Jane Doe's Portfolio</h1>
            <p>Designer | Developer | Dreamer</p>
        </header>

        <nav>
            <a href="#about">About</a>
            <a href="#projects">Projects</a>
            <a href="#contact">Contact</a>
        </nav>

        <section id="about">
            <h2>About Me</h2>
            <p>Hello! I'm Jane Doe, a front-end developer and designer based in Somewhereville. I specialize in creating intuitive, user-friendly websites and web apps. My passion lies in blending code and creativity to build meaningful digital experiences.</p>
        </section>

        <section id="projects">
            <h2>Projects</h2>

            <div class="project">
                <h3>Portfolio Website</h3>
                <p>A responsive website to showcase my personal projects and blog posts.</p>
            </div>

            <div class="project">
                <h3>Task Manager App</h3>
                <p>A to-do list application built with React and Node.js, designed to help users stay organized.</p>
            </div>

            <div class="project">
                <h3>Photography Blog</h3>
                <p>A blog layout for posting photography collections, built using HTML, CSS, and minimal JavaScript.</p>
            </div>
        </section>

        <section id="contact">
            <h2>Contact</h2>
            <p>Feel free to reach out via email or follow me on social media.</p>
            <ul>
                <li>Email: jane.doe@example.com</li>
                <li>Twitter: <a href="#">@janedoe</a></li>
                <li>LinkedIn: <a href="#">linkedin.com/in/janedoe</a></li>
            </ul>
        </section>

        <footer>
            <p>&copy; 2025 Jane Doe. All rights reserved.</p>
            <p>This page was generated by ChatGPT and not written by a human.</p>
        </footer>
    </body>
</html>
