<?php
$message = "This is a sample PHP file that is generated by AI.";
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>My E-Commerce Store</title>
        <link rel="stylesheet" href="https://saiaaaaaaa.github.io/my-website/css/sample_php_page_3.css"/>
    </head>
    <body>
        <header>
            <div class="container">
            <h1>My E-Commerce Store</h1>
                <nav>
                    <a href="#">Home</a>
                    <a href="#">Shop</a>
                    <a href="#" id="cart-link">Cart (<span id="cart-count">0</span>)</a>
                    <a href="#">Contact</a>
                </nav>
            </div>
        </header>

        <main class="container">
            <h2>Featured Products</h2>
            <div class="products">
                <div class="product" data-id="1" data-name="Stylish T-Shirt" data-price="19.99">
                    <img src="images/product1.jpg" alt="Product 1" />
                    <h3>Stylish T-Shirt</h3>
                    <p>$19.99</p>
                    <button class="add-to-cart">Add to Cart</button>
                </div>
                <div class="product" data-id="2" data-name="Classic Sneakers" data-price="49.99">
                    <img src="images/product2.jpg" alt="Product 2" />
                    <h3>Classic Sneakers</h3>
                    <p>$49.99</p>
                    <button class="add-to-cart">Add to Cart</button>
                </div>
                <div class="product" data-id="3" data-name="Leather Backpack" data-price="89.99">
                    <img src="images/product3.jpg" alt="Product 3" />
                    <h3>Leather Backpack</h3>
                    <p>$89.99</p>
                    <button class="add-to-cart">Add to Cart</button>
                </div>
            </div>
        </main>

        <footer>
            <div class="container">
                <p>&copy; 2025 My E-Commerce Store</p>
                <small>This page was generated by ChatGPT and not written by a human.</small>
            </div>
        </footer>

    </body>
    <script src="https://saiaaaaaaa.github.io/my-website/js/sample_php_page_3.js"></script>
</html>
