<?php
$message = "This is a sample PHP file that is generated by AI.";
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=7">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="theme-color" content="#005f73">
        <link rel="apple-touch-icon" sizes="57x57" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="https://saiaaaaaaa.github.io/my-website/resources/icon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="https://saiaaaaaaa.github.io/my-website/resources/icon/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="https://saiaaaaaaa.github.io/my-website/resources/icon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="https://saiaaaaaaa.github.io/my-website/resources/icon/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="https://saiaaaaaaa.github.io/my-website/resources/icon/favicon-16x16.png">
        <link rel="manifest" href="https://saiaaaaaaa.github.io/my-website/resources/icon/manifest.json">
        <meta name="msapplication-TileColor" content="#005f73">
        <meta name="msapplication-TileImage" content="https://saiaaaaaaa.github.io/my-website/resources/icon/ms-icon-144x144.png">
        <title>LearnSmart Academy</title>
        <style>
            /* This HTML file was generated by ChatGPT, not written by a human. */

            body {
                margin: 0;
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                color: #333;
            }

            header {
                background-color: #005f73;
                color: white;
                padding: 20px;
                text-align: center;
            }

            nav {
                background-color: #0a9396;
                overflow: hidden;
            }

            nav a {
                float: left;
                display: block;
                color: white;
                text-align: center;
                padding: 14px 20px;
                text-decoration: none;
            }

            nav a:hover {
                background-color: #94d2bd;
                color: black;
            }

            .hero {
                background-color: #ee9b00;
                padding: 40px 20px;
                text-align: center;
                color: white;
            }

            .hero h1 {
                margin-top: 0;
            }

            section {
                padding: 40px 20px;
                background-color: white;
                margin: 20px auto;
                max-width: 1000px;
                border-radius: 8px;
            }

            .course {
                border: 1px solid #ccc;
                padding: 15px;
                margin-bottom: 20px;
                border-radius: 5px;
            }

            .testimonials {
                background-color: #e9ecef;
            }

            blockquote {
                font-style: italic;
                margin: 20px 0;
            }

            .newsletter input[type="email"] {
                padding: 10px;
                width: 60%;
                max-width: 300px;
                margin-right: 10px;
            }

            .newsletter button {
                padding: 10px 20px;
                background-color: #005f73;
                color: white;
                border: none;
                cursor: pointer;
            }

            footer {
                background-color: #001219;
                color: white;
                text-align: center;
                padding: 20px;
            }

            footer small {
                display: block;
                margin-top: 10px;
                font-size: 12px;
            }

            /* Additional styles for accessibility and spacing */
            h2 {
                border-bottom: 2px solid #ccc;
                padding-bottom: 10px;
            }

            ul {
                list-style-type: disc;
                margin-left: 20px;
            }

        </style>
    </head>
    <body>

        <header>
            <h1>LearnSmart Academy</h1>
            <p>Empowering Minds. Shaping Futures.</p>
        </header>

        <nav>
            <a href="#courses">Courses</a>
            <a href="#testimonials">Testimonials</a>
            <a href="#newsletter">Newsletter</a>
            <a href="#contact">Contact</a>
        </nav>

        <div class="hero">
            <h1>Welcome to LearnSmart</h1>
            <p>Your journey to smarter learning begins here. Learn online, anytime.</p>
        </div>

        <section id="courses">
            <h2>Popular Courses</h2>

            <div class="course">
                <h3>Introduction to Python</h3>
                <p>Learn the basics of Python programming in this beginner-friendly course.</p>
                <ul>
                    <li>Duration: 4 weeks</li>
                    <li>Level: Beginner</li>
                    <li>Instructor: John Smith</li>
                </ul>
            </div>

            <div class="course">
                <h3>Web Development Bootcamp</h3>
                <p>Master HTML, CSS, JavaScript, and build responsive websites from scratch.</p>
                <ul>
                    <li>Duration: 8 weeks</li>
                    <li>Level: Intermediate</li>
                    <li>Instructor: Emily Johnson</li>
                </ul>
            </div>

            <div class="course">
                <h3>Data Analysis with Excel</h3>
                <p>Unlock the power of Excel to analyze and visualize real-world data.</p>
                <ul>
                    <li>Duration: 3 weeks</li>
                    <li>Level: Beginner</li>
                    <li>Instructor: Michael Lee</li>
                </ul>
            </div>
        </section>

        <section id="testimonials" class="testimonials">
            <h2>What Our Students Say</h2>

            <blockquote>
                "The Web Development Bootcamp was exactly what I needed to get hired. Highly recommend!"
                <br><strong>— Sarah W.</strong>
            </blockquote>

            <blockquote>
                "I loved the flexibility of learning on my own schedule. The Python course was so easy to follow."
                <br><strong>— Ahmed K.</strong>
            </blockquote>

            <blockquote>
                "Great instructors, clear lessons, and useful projects. LearnSmart is my go-to platform now!"
                <br><strong>— Maria G.</strong>
            </blockquote>
        </section>

        <section id="newsletter" class="newsletter">
            <h2>Join Our Newsletter</h2>
            <p>Stay updated with the latest courses, tips, and resources from LearnSmart Academy.</p>
            <form>
                <input type="email" placeholder="Enter your email" required>
                <button type="submit">Subscribe</button>
            </form>
        </section>

        <section id="contact">
            <h2>Contact Us</h2>
            <p>Have questions? We'd love to hear from you.</p>
            <ul>
                <li>Email: support@learnsmartacademy.com</li>
                <li>Phone: +1 (555) 123-4567</li>
                <li>Address: 123 Learning Lane, EduCity, EC 45678</li>
            </ul>
        </section>

        <footer>
            <p>&copy; 2025 LearnSmart Academy. All rights reserved.</p>
            <small>This page was generated by ChatGPT and not written by a human.</small>
        </footer>

    </body>
</html>
